# Jupyter Book configuration
# Reference: https://jupyterbook.org/en/stable/customize/config.html
title: "Motion Planning for Manipulators"
author: "Daoming Chen"
language: zh
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/Daoming-Chen/Motion-Planning-for-Manipulators
  path_to_book: ""
  branch: main
html:
  baseurl: ""
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
